import { useCallback, useEffect, useState, type FormEvent } from 'react';
import { Link2, Inbox, GitBranch, Clock3, Plug, ShieldCheck, Plus, Search, ChevronDown, LogOut, AlertTriangle, Check, RefreshCw, FileText, Send, Copy, Monitor, X, Download, Paperclip, ArrowUpRight, CheckCheck, Users, LoaderCircle } from 'lucide-react';
import { action, bootstrap, request, ago, shortId, ApiError, type Bootstrap, type Entity } from './api';
import { Panel, Empty, Modal, Status, EvidenceChart, DependencyGraph } from './components';
import { AppNavigation, ClientSetup, ContextPreview } from './workflow';
import { PromptBuilder } from './PromptBuilder';

const stateLabels: Record<string, string> = { overview: 'Overview', work: 'Work', inbox: 'Handoffs', graph: 'Dependencies', activity: 'Activity', connections: 'Connections', access: 'Project members', detail: 'Work detail' };
const samplePassword = 'worktether-local-2026';
function values(event: FormEvent<HTMLFormElement>) { event.preventDefault(); return Object.fromEntries(new FormData(event.currentTarget)); }
function FormField({ label, children }: { label: string; children: React.ReactNode }) { return <label className="field"><span>{label}</span>{children}</label>; }

function Login({ done }: { done: (data: Bootstrap) => void }) {
  const [register, setRegister] = useState(false);
  const [email, setEmail] = useState('akash@worktether.local');
  const [password, setPassword] = useState(samplePassword);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState('');
  const submit = async (event: FormEvent<HTMLFormElement>) => {
    const fields = values(event); setBusy(true); setError('');
    try { await request(`/api/auth/${register ? 'register' : 'login'}`, fields); done(await bootstrap()); }
    catch (cause) { setError((cause as Error).message); } finally { setBusy(false); }
  };
  return <main className="login-surface"><div className="login-brand"><Link2 size={36} /><strong>WorkTether</strong></div><section className="login-card"><span className="eyebrow">LOCAL WORKSPACE</span><h1>{register ? 'Create your account' : 'Continue your work'}</h1><p className="muted">Your projects, context, and handoffs in one place.</p><div className="segmented"><button type="button" className={!register ? 'active' : ''} onClick={() => { setRegister(false); setError(''); }}>Sign in</button><button type="button" className={register ? 'active' : ''} onClick={() => { setRegister(true); setEmail(''); setPassword(''); setError(''); }}>Create account</button></div><form onSubmit={submit}>{register && <FormField label="Name"><input name="name" required maxLength={80} autoComplete="name" placeholder="Your name" /></FormField>}<FormField label="Email"><input name="email" type="email" required autoComplete="username" value={email} onChange={event => setEmail(event.target.value)} /></FormField><FormField label="Password"><input name="password" type="password" required minLength={register ? 12 : 1} autoComplete={register ? 'new-password' : 'current-password'} value={password} onChange={event => setPassword(event.target.value)} /></FormField>{error && <p className="form-error" role="alert">{error}</p>}<button className="primary full-width" disabled={busy}>{busy ? <LoaderCircle className="spin" size={18} /> : <ShieldCheck size={18} />}{register ? 'Create account' : 'Sign in'}</button></form><details className="sample-login"><summary>Try the local sample accounts</summary><p className="small">Seeded records are examples. Each account has separate access.</p><div className="sample-buttons">{['akash', 'maya', 'ravi'].map(name => <button type="button" key={name} onClick={() => { setRegister(false); setEmail(`${name}@worktether.local`); setPassword(samplePassword); }}>{name.charAt(0).toUpperCase() + name.slice(1)}</button>)}</div><p className="small muted">Sample password: <code>{samplePassword}</code></p></details></section><p className="login-note">Runs on this computer. Shared hosting requires a separate deployment.</p></main>;
}

export default function App() {
  const [data, setData] = useState<Bootstrap | null>(null);
  const [initializing, setInitializing] = useState(true);
  const [projectId, setProjectId] = useState<string>();
  const [view, setView] = useState('overview');
  const [selectedWorkId, setSelectedWorkId] = useState('');
  const [search, setSearch] = useState('');
  const [offset, setOffset] = useState(0);
  const [sourceOffset, setSourceOffset] = useState(0);
  const [sourceResult, setSourceResult] = useState<any>({items: [], total: 0, offset: 0, nextOffset: null});
  const [modal, setModal] = useState<string | null>(null);
  const [record, setRecord] = useState<Entity | null>(null);
  const [graph, setGraph] = useState<{ nodes: Entity[]; edges: Entity[]; truncated?: boolean }>({ nodes: [], edges: [] });
  const [context, setContext] = useState<any>(null);
  const [contextStale, setContextStale] = useState(false);
  const [budget, setBudget] = useState(24000);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState('');
  const [toast, setToast] = useState('');
  const [secret, setSecret] = useState('');
  const [detailTab, setDetailTab] = useState('context');
  const [conversations, setConversations] = useState<Entity[]>([]);
  const [conversationId, setConversationId] = useState('');
  const [handoffDraft, setHandoffDraft] = useState<any>(null);
  const [handoffPreview, setHandoffPreview] = useState<any>(null);
  const [handoff, setHandoff] = useState<Entity | null>(null);

  const reload = useCallback(async (id?: string) => {
    const next = await bootstrap(id, { offset, query: search });
    setData(next);
    setSelectedWorkId(previous => next.works.some(work => work.id === previous) ? previous : next.works[0]?.id || '');
    return next;
  }, [offset, search]);
  useEffect(() => { let cancelled = false; bootstrap(projectId, { offset, query: search }).then(next => { if (!cancelled) { setData(next); setSelectedWorkId(previous => next.works.some(work => work.id === previous) ? previous : next.works[0]?.id || ''); } }).catch(cause => { if (!cancelled && (cause as ApiError).status !== 401) setError((cause as Error).message); }).finally(() => { if (!cancelled) setInitializing(false); }); return () => { cancelled = true; }; }, [projectId, offset, search]);
  useEffect(() => { if (!toast) return; const timer = setTimeout(() => setToast(''), 5000); return () => clearTimeout(timer); }, [toast]);
  useEffect(() => { setContext(null); setRecord(null); }, [data, selectedWorkId]);
  useEffect(() => { if (!data || !selectedWorkId || view !== 'graph') { setGraph({ nodes: [], edges: [] }); return; } let cancelled = false; action('get_graph', { workId: selectedWorkId }).then(result => { if (!cancelled) setGraph(result); }).catch(() => { if (!cancelled) setGraph({ nodes: [], edges: [] }); }); return () => { cancelled = true; }; }, [data, selectedWorkId, view]);

  useEffect(() => { if (!data || !selectedWorkId || view !== 'detail') return; let cancelled = false; action('list_conversations', {workId: selectedWorkId, limit: 200}).then(result => { if (!cancelled) {setConversations(result.items); setConversationId(previous => result.items.some((c: Entity) => c.id === previous) ? previous : '');} }).catch(() => {}); action('list_sources', {workId: selectedWorkId, offset: sourceOffset, limit: 40, includeHistory: true}).then(result => { if (!cancelled) setSourceResult(result); }).catch(cause => { if (!cancelled) setError(cause.message); }); return () => {cancelled = true;}; }, [data, selectedWorkId, sourceOffset, view]);

  const run = async (name: string, input: Record<string, any>, message: string) => {
    setBusy(true); setError('');
    try { const result = await action(name, input); await reload(data?.project?.id); if (message) setToast(message); return result; }
    catch (cause) { const failure = cause as ApiError; setError(failure.code === 'REVISION_CONFLICT' ? `${failure.message} Refresh the work and review the current revision before saving again.` : failure.message); throw cause; }
    finally { setBusy(false); }
  };
  const submitAction = (event: FormEvent<HTMLFormElement>, name: string, extra: Record<string, any> = {}, message = 'Saved.') => {
    const fields = values(event); void run(name, { ...fields, ...extra }, message).then(() => setModal(null)).catch(() => {});
  };
  const openModal = (name: string) => { setError(''); setSecret(''); setHandoffPreview(null); setHandoffDraft(null); setModal(name); };
  const selectWork = (work: Entity) => { setSelectedWorkId(work.id); setSourceOffset(0); setDetailTab('context'); setView('detail'); };
  const loadContext = async () => { setBusy(true); setError(''); try { setContext(await action('get_context', { workId: selectedWorkId, budgetBytes: budget })); setContextStale(false); } catch (cause) { setError((cause as Error).message); } finally { setBusy(false); } };
  const copy = async (text: string) => { try { await navigator.clipboard.writeText(text); setToast('Copied to clipboard.'); } catch { setError('Clipboard unavailable. Select and copy the text directly.'); } };

  if (initializing) return <div className="startup"><Link2 size={36} /><p>Opening your workspace…</p></div>;
  if (!data) return <Login done={next => { setData(next); setSelectedWorkId(next.works[0]?.id || ''); }} />;

  const project = data.project;
  const work = data.works.find(item => item.id === selectedWorkId);
  const workSources: Entity[] = sourceResult.items.filter((source: Entity) => source.workId === selectedWorkId);
  const workAttachments = data.attachments.filter(file => file.workId === selectedWorkId);
  const currentSources = workSources.filter(source => source.status !== 'superseded' && source.active !== false);
  const filteredWorks = data.works;
  const sent = data.handoffs.filter(item => item.senderId === data.user.id && !item.revoked);
  const incoming = data.handoffs.filter(item => item.recipientId === data.user.id && !item.revoked);
  const attention = data.works.filter(item => item.needsReview || data.sources.some(source => source.workId === item.id && source.status === 'needs_review' && source.active !== false));
  const owner = work?.ownerId === data.user.id;
  const projectOwner = project?.ownerId === data.user.id;
  const resumeWork = data.works.find(item => item.id === selectedWorkId && item.status !== 'done') || data.works.find(item => item.status !== 'done') || work;
  const activeDevices = data.devices.filter(device => !device.revoked);
  const activeCredentials = data.credentials.filter(credential => !credential.revoked);
  const memberName = (id: string) => data.members.find(member => member.id === id)?.name || (id === data.user.id ? data.user.name : 'Collaborator');
  const openedRecord = record && (data.sources.find(source => source.id === record.id) || record);
  const recentEvents = data.events.slice(0, 24);

  const WorkTable = ({ compact = false }: { compact?: boolean }) => <div className="work-list">
    {(compact ? filteredWorks.slice(0, 5) : filteredWorks).length ? <table>
      <thead><tr><th>Work</th><th>Status</th><th>Revision</th></tr></thead>
      <tbody>{(compact ? filteredWorks.slice(0, 5) : filteredWorks).map(item => <tr key={item.id}>
        <td><button className="work-link" onClick={() => selectWork(item)}><strong>{item.title}</strong><span className="work-subtitle"><span className="record-access"><ShieldCheck size={12} />{item.ownerId === data.user.id ? (item.visibility === 'project' ? 'Shared with project' : 'Private') : 'Shared with you'}</span><span className="mono small muted">{shortId(item.id)}</span></span></button></td>
        <td><Status value={item.needsReview ? 'needs_review' : item.status} /></td><td className="revision-cell small muted">v{item.revision}</td>
      </tr>)}</tbody>
    </table> : <Empty title={search ? 'No matching work' : 'Start with one objective'} message={search ? 'Try a title or Work ID you can access.' : 'Create work to keep its goal, sources, and next step together.'} action={!search && <button className="primary" onClick={() => openModal('create-work')}><Plus size={16} />Create work</button>} />}
  </div>;
  const GraphPanel = ({ expanded = false }: { expanded?: boolean }) => <Panel title={expanded ? 'Recorded dependencies' : `Context graph${work ? ` · ${work.title}` : ''}`} action={!expanded && work && <button className="text-button" onClick={() => setView('graph')}>Explore graph</button>}><DependencyGraph nodes={graph.nodes} edges={graph.edges} select={setRecord} selectedId={record?.id} />{graph.truncated && <p className="small muted graph-caption">Showing a bounded neighborhood. Additional permitted nodes or edges were omitted.</p>}{openedRecord && <div className="graph-detail"><div className="row between"><strong>{openedRecord.title || openedRecord.name}</strong><button className="icon-button" aria-label="Close record detail" onClick={() => setRecord(null)}><X size={16} /></button></div><p className="small muted mono">{openedRecord.id}</p><p className="preserve">{openedRecord.content || openedRecord.objective || project?.requirements}</p>{openedRecord.status && <Status value={openedRecord.status} />}</div>}</Panel>;
  const openHandoff = async (item: Entity) => { setBusy(true); setError(''); try {const snapshot = await action('get_handoff', {handoffId: item.id}); setHandoff(snapshot); openModal('handoff-detail'); await reload(project?.id);} catch (cause) {setError((cause as Error).message);} finally {setBusy(false);} };


  return <div className="app-shell"><a className="skip-link" href="#main-content">Skip to content</a>
    <header className="app-header"><button className="brand" onClick={() => setView('overview')}><Link2 size={30} /><strong>WorkTether</strong></button><div className="workspace-picker"><Users size={17} /><span>Local workspace</span></div><div className="project-picker"><FileText size={17} /><select aria-label="Select project" value={project?.id || ''} onChange={event => { setProjectId(event.target.value); setOffset(0); setSearch(''); setView('overview'); }}><option value="" disabled>Select project</option>{data.projects.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select><ChevronDown size={14} /></div><div className="header-end"><span className="local-badge">Local first{project?.sample ? ' · sample project' : ''}</span><span className="avatar">{data.user.name.charAt(0)}</span><span className="user-name">{data.user.name}</span><button className="icon-button" aria-label="Sign out" onClick={async () => { await request('/api/auth/logout', {}); setData(null); setProjectId(undefined); setView('overview'); }}><LogOut size={17} /></button></div></header>
    <AppNavigation view={view} unread={incoming.filter(item => item.state === 'queued').length} navigate={next => { setView(next); setError(''); }} createProject={() => openModal('create-project')} />
    <main className="main-surface" id="main-content" tabIndex={-1}><div className="page-heading"><div><p className="breadcrumb">{project?.name || 'Your workspace'}</p><h1>{view === 'detail' ? work?.title || 'Work detail' : stateLabels[view]}</h1><p className="page-description">{view === 'overview' ? 'Pick up your work or start a new objective.' : view === 'work' ? 'All work you can access, with a stable ID for each objective.' : view === 'graph' ? 'See which recorded sources and decisions depend on each other.' : view === 'connections' ? 'Connect Codex, Cursor, or Claude in three steps.' : view === 'inbox' ? 'Selected information you have sent or received.' : view === 'activity' ? 'Changes to records you can access.' : view === 'access' ? 'Choose who belongs to the project. Work has its own sharing settings.' : work?.objective}</p></div><div className="page-actions">{['overview', 'work'].includes(view) && project && <button className="primary" onClick={() => openModal('create-work')}><Plus size={17} />Create work</button>}<button className="icon-button" aria-label="Refresh workspace" disabled={busy} onClick={() => void reload(project?.id).then(() => setToast('Workspace refreshed.')).catch(cause => setError(cause.message))}><RefreshCw size={18} className={busy ? 'spin' : ''} /></button></div></div>
      {error && !modal && <div className="error-banner" role="alert"><AlertTriangle size={18} /><span>{error}</span><button className="icon-button" aria-label="Dismiss error" onClick={() => setError('')}><X size={16} /></button></div>}
      {!project && view !== 'connections' ? <Panel title="Your workspace is ready"><Empty title="Create or join a project" message="Create a project to start work. An existing project owner can add your registered email." action={<button className="primary" onClick={() => openModal('create-project')}><Plus size={17} />Create project</button>} /></Panel> : <>
      {view === 'overview' && <div className="overview-grid">
        <div className="primary-column">
          {attention.length > 0 && <div className="attention-banner"><AlertTriangle size={21} /><div><strong>{attention.length} work {attention.length === 1 ? 'item needs' : 'items need'} review</strong><span>Requirements or sources changed in the work shown on this page.</span></div><button className="secondary amber" onClick={() => selectWork(attention[0])}>Review work</button></div>}
          {resumeWork && <section className="continue-card"><div className="continue-copy"><span className="eyebrow">PICK UP WHERE YOU LEFT OFF</span><h2>{resumeWork.title}</h2><p className="next-step-preview">{resumeWork.nextAction || resumeWork.objective}</p><div className="row"><Status value={resumeWork.needsReview ? 'needs_review' : resumeWork.status} /><span className="small muted">{resumeWork.ownerId === data.user.id && resumeWork.visibility === 'private' ? 'Private to you' : 'Work you can access'}</span></div></div><button className="primary" onClick={() => selectWork(resumeWork)}>Continue work<ArrowUpRight size={17} /></button></section>}
          <Panel title="Work" action={<button className="text-button" onClick={() => { setSearch(''); setOffset(0); setView('work'); }}>View all work<ArrowUpRight size={15} /></button>}><WorkTable compact /></Panel>
          <Panel title="Project goal" action={projectOwner && <button className="text-button" onClick={() => openModal('edit-project')}>Edit requirements</button>}><div className="project-brief"><p>{project?.objective}</p><details><summary>View requirements <span className="revision-label">v{project?.revision}</span></summary><p className="preserve">{project?.requirements || 'No shared requirements recorded yet.'}</p></details></div></Panel>
        </div>
        <aside className="insight-column">
          <Panel title="Recent handoffs" action={<button className="text-button" onClick={() => setView('inbox')}>View all</button>}>{incoming.length ? <div className="inbox-preview">{incoming.slice(0, 2).map(item => <div key={item.id}><p className="small muted">From {memberName(item.senderId)}</p><strong>{item.title}</strong>{item.stale && <Status value="needs_review" />}<p className="small muted">{ago(item.createdAt)}</p><button className="secondary full-width" onClick={() => void openHandoff(item)}>Open handoff</button></div>)}</div> : <Empty title="No handoffs on this page" message="Information shared with you appears here." />}</Panel>
          <Panel title="Work with your AI"><div className="connection-preview"><p className="small muted">Prepare a prompt with project context, or connect your AI client.</p>{resumeWork && <button className="primary prompt-primary full-width" onClick={() => { selectWork(resumeWork); setDetailTab('prompt'); }}>Open prompt builder<ArrowUpRight size={16} /></button>}<button className="secondary full-width" onClick={() => setView('connections')}><Plug size={16} />Set up a connection</button></div></Panel>
          <details className="overview-evidence"><summary><CheckCheck size={17} />Evidence status</summary><EvidenceChart counts={data.evidenceCounts} /></details>
          <p className="privacy-note"><ShieldCheck size={17} />Private work stays private until you share it.</p>
        </aside>
      </div>}
      {view === 'work' && <Panel title={`Work you can access · ${data.workPage.total}`} action={<div className="search-input"><Search size={16} /><input aria-label="Search work" placeholder="Search title or Work ID" value={search} onChange={event => { setSearch(event.target.value); setOffset(0); }} /></div>}><WorkTable /><div className="pagination"><span className="small muted">Showing {data.works.length ? data.workPage.offset + 1 : 0}–{data.workPage.offset + data.works.length} of {data.workPage.total} permitted work items</span><button className="secondary" disabled={offset === 0} onClick={() => setOffset(Math.max(0, offset - 40))}>Previous</button><button className="secondary" disabled={data.workPage.nextOffset === null} onClick={() => setOffset(data.workPage.nextOffset!)}>Next</button></div></Panel>}
      {view === 'detail' && work && <><div className="work-meta"><span className="work-identity"><span className="small muted">Work ID</span><code>{work.id}</code><button className="icon-button" aria-label="Copy full Work ID" onClick={() => void copy(work.id)}><Copy size={15} /></button></span><Status value={work.needsReview ? 'needs_review' : work.status} /><span>v{work.revision}</span><span>{memberName(work.ownerId)}</span><span>{work.visibility === 'private' ? 'Private work' : 'Shared with project'}</span><div className="grow" /><>{work.canEdit && <button className="secondary" onClick={() => openModal('edit-work')}>Edit work</button>}</>{owner && <button className="primary" onClick={() => openModal('send-handoff')}><Send size={16} />Share handoff</button>}</div>{work.needsReview && <div className="attention-banner compact"><AlertTriangle size={19} /><strong>Review the changed sources before continuing.</strong>{work.canEdit && <button className="secondary" onClick={() => openModal('review-work')}>Record work review</button>}<button className="text-button" onClick={() => setView('graph')}>View dependencies</button></div>}{work.canEdit && work.reviewedProjectRevision !== project?.revision && <Panel title="Project requirements changed"><div className="access-content"><p className="preserve">{project?.requirements}</p><p>Review this work against requirements v{project?.revision}, then acknowledge the baseline. Source reviews remain separate.</p><button className="primary" disabled={busy} onClick={() => void run('update_work', {workId: work.id, expectedRevision: work.revision, reviewedProjectRevision: project?.revision}, 'Current requirements acknowledged.').catch(() => {})}>Acknowledge requirements v{project?.revision}</button></div></Panel>}<div className="tabs" role="tablist" aria-label="Work views">{['context', 'prompt', 'sources', 'history', 'access'].map(tab => <button role="tab" aria-selected={detailTab === tab} key={tab} onClick={() => setDetailTab(tab)}>{tab === 'access' ? 'Sharing' : tab === 'prompt' ? 'Prompt builder' : tab.charAt(0).toUpperCase() + tab.slice(1)}</button>)}</div>
        {detailTab === 'context' && <>
          <div className="work-flow" aria-label="Work continuation steps"><span><span className="flow-number">1</span>Save useful sources</span><span><span className="flow-number">2</span>Build current context</span><span><span className="flow-number">3</span>Copy it into your AI client</span></div>
          <div className="detail-grid">
            <Panel title="Current context" action={<button className="primary" disabled={busy} onClick={() => void loadContext()}><RefreshCw size={16} />Build context</button>}>
              <div className="context-body">
                {contextStale && <div className="context-warning" role="status"><AlertTriangle size={18} /><p>This saved context is out of date. Build current context before continuing.</p></div>}
                {context ? <><div className="context-toolbar"><span className="small muted">{context.sources?.length || 0} included sources · {context.bytesUsed ?? new TextEncoder().encode(JSON.stringify(context)).length} bytes</span><button className="secondary" onClick={() => void copy(JSON.stringify(context))}><Copy size={15} />Copy package</button></div><p className="context-id small muted">Context ID <code>{context.id}</code> · Work v{context.workRevision} · Requirements v{context.projectRevision}</p><ContextPreview context={context} /></> : <Empty title="Bring the right information into your next chat" message="Build a package with this work’s goal, requirements, selected sources, and next step." action={work.canEdit && <button className="secondary" onClick={() => openModal('add-source')}><Plus size={16} />Save a source first</button>} />}
                <details className="context-options"><summary>Context options</summary><label className="inline-label">Package budget<input aria-label="Context byte budget" type="number" min={256} max={1000000} step={1000} value={budget} onChange={event => setBudget(Number(event.target.value))} /><span className="small muted">UTF-8 bytes</span></label><p className="small muted">This limits the saved package, not your model’s token window. Mandatory requirements are preserved.</p><button className="text-button" onClick={() => openModal('open-context')}>Open a saved package by Context ID</button></details>
              </div>
            </Panel>
            <div className="primary-column">
              <Panel title="Next step" action={work.canEdit && <button className="text-button" onClick={() => openModal('edit-work')}>Edit</button>}><div className="next-action"><p className="preserve">{work.nextAction || 'Record what should happen next.'}</p><button className="text-button" onClick={() => setView('graph')}><GitBranch size={15} />View dependencies</button></div></Panel>
              <Panel title="Useful sources" action={work.canEdit && <button className="text-button" onClick={() => openModal('add-source')}><Plus size={15} />Add</button>}><div className="next-action"><div className="source-summary">{currentSources.slice(0, 5).map(source => <button key={source.id} onClick={() => { setRecord(source); setDetailTab('sources'); }}><FileText size={16} /><span>{source.title}</span><Status value={source.status} /></button>)}{!currentSources.length && <p className="small muted">Save a prompt, decision, assumption, or evidence you want to keep.</p>}</div><button className="text-button" onClick={() => setDetailTab('sources')}>View all source records</button></div></Panel>
            </div>
          </div>
          <details className="conversation-section"><summary>Link a conversation <span className="small muted">Optional</span></summary><div className="access-content"><p className="small muted">Use a Conversation ID to group selected excerpts from a chat. MCP does not capture the chat automatically.</p><div className="row"><select aria-label="Current conversation" value={conversationId} onChange={event => setConversationId(event.target.value)}><option value="">No conversation selected</option>{conversations.map(c => <option key={c.id} value={c.id}>{c.title} · {shortId(c.id)}</option>)}</select>{work.canEdit && <button className="secondary" onClick={() => openModal('create-conversation')}><Plus size={16} />New conversation</button>}</div>{conversationId && <div className="row conversation-id"><code>{conversationId}</code><button className="icon-button" aria-label="Copy full Conversation ID" onClick={() => void copy(conversationId)}><Copy size={15} /></button></div>}</div></details>
        </>}
        {detailTab === 'prompt' && <PromptBuilder key={work.id} work={work} projectRevision={project?.revision || 1} conversationId={conversationId} saved={() => void reload(project?.id).catch(cause => setError(cause.message))} />}
        {detailTab === 'sources' && <Panel title="Sources and evidence" action={work.canEdit && <button className="primary" onClick={() => openModal('add-source')}><Plus size={16} />Add source</button>}><div className="source-list">{currentSources.length ? currentSources.map(source => <article className="source-record" key={source.id}><div className="row between"><div><span className="eyebrow">{source.kind}</span><h3>{source.title}</h3></div><Status value={source.status} /></div><p className="preserve">{source.content}</p><div className="row source-actions"><span className="mono small muted">{shortId(source.id)} · v{source.revision}{source.conversationId && ` · ${shortId(source.conversationId)}`}</span><>{work.canEdit && <button className="text-button" onClick={() => { setRecord(source); openModal('correct-source'); }}>Correct source</button>}</>{work.canEdit && <button className="text-button danger" onClick={() => {setRecord(source); openModal('exclude-source');}}>Exclude from context</button>}{work.canEdit && source.status === 'needs_review' && <button className="text-button" onClick={() => { setRecord(source); openModal('resolve-review'); }}>Resolve review</button>}</div></article>) : <Empty title="No sources recorded" message="Add an assumption, decision, prompt, summary, or verification result." />}</div>{workSources.filter(source => source.active === false).map(source => <article className="source-record" key={source.id}><div className="row between"><strong>{source.title}</strong><Status value="excluded"/></div><p className="small muted">{source.exclusionReason || 'Excluded from current context.'}</p>{work.canEdit && <button className="text-button" onClick={() => void run('set_source_active', {sourceId: source.id, expectedRevision: source.revision, active: true, reason: 'Restored for review from the dashboard.'}, 'Source restored for review.').catch(() => {})}>Restore for review</button>}</article>)}<div className="pagination"><span className="small muted">Source history page {sourceResult.offset / 40 + 1} · {sourceResult.total} permitted records</span><button className="secondary" disabled={sourceOffset === 0} onClick={() => setSourceOffset(Math.max(0, sourceOffset - 40))}>Previous</button><button className="secondary" disabled={sourceResult.nextOffset === null} onClick={() => setSourceOffset(sourceResult.nextOffset)}>Next</button></div><div className="attachment-bar">{work.canEdit && <button className="secondary" onClick={() => openModal('attachment')}><Paperclip size={16} />Attach a file</button>}<span className="small muted">Text, Markdown, PDF, PNG, JPEG · up to 5 MiB</span></div>{workAttachments.map(file => <a key={file.id} className="attachment-link" href={`/api/attachments/${encodeURIComponent(file.id)}`}><Download size={16} />{file.name} · {file.size} bytes</a>)}</Panel>}
        {detailTab === 'history' && <Panel title="Immutable record revisions"><div className="source-list">{data.revisions.filter(r => r.recordId === work.id || r.snapshot?.workId === work.id).map(revision => <article className="history-record" key={revision.id}><div className="row between"><strong>{revision.snapshot.title || revision.type}</strong><span className="small mono">v{revision.revision}</span></div><p className="preserve small">{revision.snapshot.content || revision.snapshot.objective}</p>{revision.snapshot.reviewNote && <p className="small preserve">Review: {revision.snapshot.reviewNote}</p>}<span className="mono small muted">{shortId(revision.recordId)} · {ago(revision.createdAt)}</span></article>)}<p className="small muted">Latest permitted revisions in this workspace page. {data.revisionPage.nextOffset !== null && 'Additional revisions are available through workspace_overview revisionOffset.'}</p></div></Panel>}
        {detailTab === 'access' && <Panel title="Work access"><div className="access-content"><p><strong>{memberName(work.ownerId)}</strong> owns this work. {work.visibility === 'project' ? 'Project members may read its shared records.' : 'It is private unless an explicit grant is added.'}</p>{(work.grants || []).map((grant: Entity) => <div className="access-row" key={grant.userId || grant.id}><span>{memberName(grant.userId || grant.id)}</span><Status value={grant.permission} />{owner && <button className="text-button danger" onClick={() => void run('revoke_grant', { workId: work.id, userId: grant.userId || grant.id }, 'Work access revoked.').catch(() => {})}>Revoke</button>}</div>)}{owner && <div className="row"><button className="secondary" onClick={() => openModal('share-work')}><Users size={16} />Grant access</button><button className="secondary" onClick={() => openModal('reassign-work')}>Transfer ownership</button></div>}</div></Panel>}
      </>}
      {view === 'inbox' && <><Panel title="Received handoffs"><div className="handoff-list">{incoming.length ? incoming.map(item => <button key={item.id} className="handoff-row" onClick={() => void openHandoff(item)}><span className="handoff-icon"><Inbox size={21} /></span><span className="handoff-description"><strong>{item.title}</strong><span className="small muted">From {memberName(item.senderId)} · {ago(item.createdAt)} · snapshot v{item.workRevision}</span></span><Status value={item.stale ? 'needs_review' : item.state} /><ArrowUpRight size={17} /></button>) : <Empty title="No received handoffs in this page" message="A collaborator can send selected context to your account." />}</div></Panel><Panel title="Sent handoffs"><div className="handoff-list">{sent.length ? sent.map(item => <button key={item.id} className="handoff-row" onClick={() => void openHandoff(item)}><Send size={20}/><span className="handoff-description"><strong>{item.title}</strong><span className="small muted">To {memberName(item.recipientId)} · snapshot v{item.workRevision}</span></span><Status value={item.stale ? 'needs_review' : item.state}/></button>) : <Empty title="No sent handoffs in this page" message="Share selected text, sources or files from a work item."/>}</div></Panel><div className="pagination"><span className="small muted">{data.handoffPage.total} permitted sent and received snapshots</span><button className="secondary" disabled={data.handoffPage.offset === 0} onClick={() => void bootstrap(project?.id, {offset, query: search, handoffOffset: Math.max(0, data.handoffPage.offset - 100)}).then(setData).catch(cause => setError(cause.message))}>Previous</button><button className="secondary" disabled={data.handoffPage.nextOffset === null} onClick={() => void bootstrap(project?.id, {offset, query: search, handoffOffset: data.handoffPage.nextOffset!}).then(setData).catch(cause => setError(cause.message))}>Next</button></div></>}
      {view === 'graph' && <><div className="graph-selection"><label htmlFor="graph-work">Work item</label><select id="graph-work" value={selectedWorkId} onChange={event => { setSelectedWorkId(event.target.value); setRecord(null); }}>{data.works.map(item => <option key={item.id} value={item.id}>{item.title}</option>)}</select>{work && <button className="secondary" onClick={() => selectWork(work)}>Open work</button>}</div><GraphPanel expanded /></>}
      {view === 'activity' && <Panel title="Recent activity"><div className="activity-list">{recentEvents.length ? recentEvents.map(event => <article key={event.id}><div className="activity-dot"><Clock3 size={17} /></div><div><strong>{event.title || event.action?.replaceAll('_', ' ') || event.kind || 'Record updated'}</strong><p className="small muted">{memberName(event.actorId || event.userId)} · {ago(event.createdAt)}</p>{event.message && <p className="small">{event.message}</p>}</div></article>) : <Empty title="No activity yet" message="Changes to accessible project records will appear here." />}</div></Panel>}
      {view === 'connections' && <div className="detail-grid connections-grid">
        <div className="primary-column"><ClientSetup createCredential={setup => openModal(setup ? 'setup-credential' : 'create-credential')} registerDevice={() => openModal('register-device')} copy={text => void copy(text)} />
          <details className="credential-management"><summary>Manage credentials <span className="small muted">{activeCredentials.length} active</span></summary><div className="device-list">{activeCredentials.map(credential => <div className="device-row" key={credential.id}><ShieldCheck size={20} /><div className="grow"><strong>{credential.name || 'MCP credential'}</strong><p className="small muted">Created {ago(credential.createdAt)}</p></div><button className="text-button danger" disabled={busy} onClick={() => void run('revoke_credential', { credentialId: credential.id }, 'Credential revoked.').catch(() => {})}>Revoke</button></div>)}{!activeCredentials.length && <p className="empty-inline">No active credentials.</p>}</div></details>
        </div>
        <aside className="insight-column"><Panel title="Registered clients"><div className="device-list">{activeDevices.length ? activeDevices.map(device => <div className="device-row" key={device.id}><Monitor size={21} /><div className="grow"><strong>{device.name}</strong><p className="small muted">{device.platform} · {device.client}</p><p className="small muted">Last request: {ago(device.lastSeenAt)}</p></div><button className="text-button danger" disabled={busy} onClick={() => void run('revoke_device', { deviceId: device.id }, 'Client registration and its credentials revoked.').catch(() => {})}>Revoke</button></div>) : <Empty title="No clients registered yet" message="Complete the setup steps. Your registrations will appear here." />}</div></Panel>
          <div className="connection-note"><ShieldCheck size={20} /><h3>Your account controls access</h3><p>Each person connects with their own credential. Work IDs remain the same across clients.</p><p className="small muted">This service runs on this computer. Other physical machines need shared hosting.</p><details><summary>Service details</summary><dl className="service-details"><div><dt>MCP tools</dt><dd>20 available</dd></div><div><dt>Transport</dt><dd>HTTP + stdio</dd></div><div><dt>Dashboard</dt><dd>Browser</dd></div><div><dt>Automatic chat capture</dt><dd>Planned</dd></div><div><dt>Remote execution</dt><dd>Not available</dd></div></dl></details></div>
        </aside>
      </div>}
      {view === 'access' && <div className="detail-grid"><Panel title="Project members" action={projectOwner && <button className="primary" onClick={() => openModal('add-member')}><Plus size={16} />Add member</button>}><div className="member-list">{data.members.map(member => <div className="member-row" key={member.id}><span className="avatar">{member.name?.charAt(0)}</span><div className="grow"><strong>{member.name}</strong><p className="small muted">{member.email}</p></div><span className="small muted">{member.id === project?.ownerId ? 'Project owner' : 'Member'}</span></div>)}</div></Panel><Panel title="Sharing rules"><div className="connection-setup"><p>Project membership gives access to shared requirements. Private work needs an explicit grant.</p><p>Edit access allows changes to a work item. Its owner controls sharing, access grants, and ownership transfer.</p><p className="small muted">Removing access blocks future retrieval. It cannot remove information someone already copied.</p></div></Panel></div>}
      </>}
      <footer className="app-footer"><span>WorkTether · Local workspace</span><span>Durable records · Explicit sharing</span></footer>
    </main>
    {toast && <div className="toast" role="status"><Check size={17} />{toast}</div>}
    {modal && <Modal title={{ 'create-project': 'Create project', 'create-conversation': 'Create conversation identity', 'exclude-source': 'Exclude source from current context', 'review-work': 'Record work review', 'open-context': 'Open saved context snapshot', 'edit-project': 'Update shared requirements', 'create-work': 'Create work', 'edit-work': 'Update work', 'add-source': 'Add a source record', 'correct-source': 'Correct source', 'resolve-review': 'Resolve source review', 'send-handoff': 'Share a selected handoff', 'handoff-detail': handoff?.title || 'Handoff', 'register-device': 'Register a client', 'create-credential': 'Create a client credential', 'setup-credential': 'Create a setup credential', 'share-work': 'Grant work access', 'reassign-work': 'Transfer work ownership', 'add-member': 'Add a project member', attachment: 'Attach a file' }[modal] || 'Details'} close={() => { setModal(null); setError(''); }}>
      {error && <p className="form-error" role="alert">{error}</p>}
      {modal === 'create-project' && <form onSubmit={event => { const fields = values(event); void run('create_project', fields, 'Project created.').then(result => { setProjectId(result.id); setModal(null); setView('overview'); }).catch(() => {}); }}><FormField label="Project name"><input name="name" required maxLength={100} placeholder="e.g. Commerce API" /></FormField><FormField label="Objective"><textarea name="objective" required maxLength={4000} placeholder="What should this project achieve?" /></FormField><button className="primary" disabled={busy}>Create project</button></form>}
      {modal === 'edit-project' && project && <form onSubmit={event => submitAction(event, 'update_project', { projectId: project.id, expectedRevision: project.revision }, 'Shared requirements updated.')}><p className="small muted">Updating requirements v{project.revision}. Recorded project work will need review.</p><FormField label="Project objective"><textarea name="objective" required defaultValue={project.objective} maxLength={4000} /></FormField><FormField label="Shared requirements and constraints"><textarea name="requirements" required defaultValue={project.requirements} rows={7} maxLength={20000} /></FormField><button className="primary" disabled={busy}>Save new revision</button></form>}
      {(modal === 'create-work' || modal === 'edit-work') && <form onSubmit={event => submitAction(event, modal === 'create-work' ? 'create_work' : 'update_work', modal === 'create-work' ? { projectId: project?.id } : { workId: work?.id, expectedRevision: work?.revision }, modal === 'create-work' ? 'Work created.' : 'Work revision saved.')}><FormField label="Title"><input name="title" required maxLength={200} defaultValue={modal === 'edit-work' ? work?.title : ''} /></FormField><FormField label="Objective"><textarea name="objective" required maxLength={4000} defaultValue={modal === 'edit-work' ? work?.objective : ''} /></FormField><FormField label="Next action"><textarea name="nextAction" maxLength={4000} defaultValue={modal === 'edit-work' ? work?.nextAction : ''} /></FormField>{modal === 'create-work' ? <FormField label="Visibility"><select name="visibility" defaultValue="private"><option value="private">Private to me</option><option value="project">Readable by project members</option></select></FormField> : <FormField label="State"><select name="status" defaultValue={work?.status}>{['planned', 'active', 'review', 'blocked', 'done'].map(status => <option key={status}>{status}</option>)}</select></FormField>}<button className="primary" disabled={busy}>{modal === 'create-work' ? 'Create work' : `Save revision after v${work?.revision}`}</button></form>}
      {modal === 'open-context' && work && <form onSubmit={event => {const fields = values(event); setBusy(true); setError(''); void action('get_context_snapshot', {contextId: fields.contextId}).then(result => {if (result.snapshot.workId !== work.id) throw new Error('This snapshot belongs to a different Work ID. Open that work first.'); setContext(result.snapshot); setContextStale(result.stale); setModal(null);}).catch(cause => setError(cause.message)).finally(() => setBusy(false));}}><FormField label="Saved Context ID"><input name="contextId" required placeholder="ctx_…"/></FormField><p className="small muted">Access follows current work permissions. A saved package remains an immutable historical snapshot.</p><button className="primary" disabled={busy}>Open snapshot</button></form>}
      {modal === 'review-work' && work && <form onSubmit={event => submitAction(event, 'update_work', {workId: work.id, expectedRevision: work.revision, reviewedProjectRevision: project?.revision}, 'Work review recorded; unresolved source flags remain.')}><p className="preserve">{project?.requirements}</p><p>Review this work against requirements v{project?.revision}. Outstanding source reviews remain flagged.</p><FormField label="Work review note"><textarea name="reviewNote" required rows={4} maxLength={40000}/></FormField><button className="primary" disabled={busy}>Record work review</button></form>}
      {modal === 'create-conversation' && work && <form onSubmit={event => {const fields = values(event); if (!fields.clientReference) delete fields.clientReference; void run('create_conversation', {...fields, workId: work.id}, 'Conversation identity created.').then(result => {setConversationId(result.id); setModal(null);}).catch(() => {});}}><FormField label="Conversation title"><input name="title" required maxLength={200}/></FormField><FormField label="Optional client reference"><input name="clientReference" maxLength={1000} placeholder="Chat URL or reference"/></FormField><p className="small muted">This record links selected sources to a conversation. It does not read the chat itself.</p><button className="primary" disabled={busy}>Create conversation ID</button></form>}
      {modal === 'exclude-source' && record && <form onSubmit={event => submitAction(event, 'set_source_active', {sourceId: record.id, expectedRevision: record.revision, active: false}, 'Source excluded; recorded dependents flagged.')}><p>Exclude <strong>{record.title}</strong> from future context packages. Its ID and history remain available.</p><FormField label="Reason"><textarea name="reason" required rows={3} maxLength={2000}/></FormField><button className="primary" disabled={busy}>Exclude from context</button></form>}
      {modal === 'add-source' && <form onSubmit={event => { const fields = values(event); const dependencies = fields.dependsOn ? [String(fields.dependsOn)] : []; delete fields.dependsOn; void run('add_source', { ...fields, workId: work?.id, dependsOn: dependencies, ...(conversationId ? {conversationId} : {}) }, 'Source recorded.').then(() => setModal(null)).catch(() => {}); }}><div className="form-columns"><FormField label="Record kind"><select name="kind">{['prompt', 'assumption', 'decision', 'evidence', 'summary'].map(kind => <option key={kind}>{kind}</option>)}</select></FormField><FormField label="State"><select name="status">{['proposed', 'accepted', 'verified', 'needs_review'].map(status => <option key={status}>{status}</option>)}</select></FormField></div><FormField label="Title"><input name="title" required maxLength={200} /></FormField><FormField label="Content"><textarea name="content" required rows={6} maxLength={40000} /></FormField><FormField label="Depends on a source"><select name="dependsOn"><option value="">No recorded dependency</option>{data.sources.filter(source => source.status !== 'superseded' && source.active !== false).map(source => <option value={source.id} key={source.id}>{source.title}</option>)}</select></FormField><button className="primary" disabled={busy}>Record source</button></form>}
      {modal === 'correct-source' && record && <form onSubmit={event => submitAction(event, 'correct_source', { sourceId: record.id, expectedRevision: record.revision }, 'Correction saved and recorded dependents flagged.')}><p className="small muted">The earlier record is preserved. Recorded downstream dependencies will need review.</p><FormField label="Corrected content"><textarea name="content" required rows={6} defaultValue={record.content} maxLength={40000} /></FormField><FormField label="Reason"><textarea name="reason" required maxLength={2000} /></FormField><button className="primary" disabled={busy}>Save correction</button></form>}
      {modal === 'resolve-review' && record && <form onSubmit={event => submitAction(event, 'resolve_review', { sourceId: record.id, expectedRevision: record.revision }, 'Source review resolved.')}><p>Confirm the record against current requirements before changing its state.</p><FormField label="Reviewed state"><select name="status"><option value="accepted">Accepted</option><option value="verified">Verified</option><option value="proposed">Proposed</option></select></FormField><FormField label="Review note and evidence"><textarea name="note" required rows={3} maxLength={40000} placeholder="What did you check, and what supports this state?" /></FormField><button className="primary" disabled={busy}>Record resolution</button></form>}
      {modal === 'send-handoff' && work && !handoffPreview && <form onSubmit={event => { event.preventDefault(); const fields = new FormData(event.currentTarget); const input = { workId: work.id, recipientId: fields.get('recipientId'), title: fields.get('title'), content: fields.get('content'), sourceIds: fields.getAll('sourceIds'), attachmentIds: fields.getAll('attachmentIds'), idempotencyKey: fields.get('idempotencyKey'), expectedRevision: work.revision, expectedSourceRevisions: Object.fromEntries(currentSources.filter(source => fields.getAll('sourceIds').includes(source.id)).map(source => [source.id, source.revision])) }; setHandoffPreview({input, sources: currentSources.filter(source => input.sourceIds.includes(source.id)), files: workAttachments.filter(file => input.attachmentIds.includes(file.id))}); }}><input type="hidden" name="idempotencyKey" defaultValue={handoffDraft?.idempotencyKey || crypto.randomUUID()} /><p className="small muted">Select the text, source snapshots and files to send to this collaborator.</p><FormField label="Recipient"><select name="recipientId" required defaultValue={handoffDraft?.recipientId || ""}><option value="">Choose project collaborator</option>{data.members.filter(member => member.id !== data.user.id).map(member => <option key={member.id} value={member.id}>{member.name}</option>)}</select></FormField><FormField label="Title"><input name="title" required defaultValue={handoffDraft?.title || `Continue: ${work.title}`} maxLength={200} /></FormField><FormField label="Selected handoff text"><textarea name="content" required rows={5} maxLength={40000} defaultValue={handoffDraft?.content || ""} placeholder="What should the recipient know or review?" /></FormField><fieldset className="source-checkboxes"><legend>Include source snapshots</legend>{currentSources.map(source => <label key={source.id}><input type="checkbox" name="sourceIds" value={source.id} defaultChecked={handoffDraft?.sourceIds.includes(source.id) || false} /><span>{source.title}</span></label>)}</fieldset><fieldset className="source-checkboxes"><legend>Include files</legend>{workAttachments.map(file => <label key={file.id}><input type="checkbox" name="attachmentIds" value={file.id} defaultChecked={handoffDraft?.attachmentIds.includes(file.id) || false}/><span>{file.name}</span></label>)}</fieldset><p className="small muted">Sending records a snapshot of revision v{work.revision}. Review your selection before sending.</p><button className="primary" disabled={busy}><Send size={16} />Preview selected content</button></form>}
      {modal === 'send-handoff' && work && handoffPreview && <div className="handoff-detail"><p className="small muted">To {memberName(handoffPreview.input.recipientId)} · Work v{handoffPreview.input.expectedRevision}</p><h3>{handoffPreview.input.title}</h3><p className="preserve">{handoffPreview.input.content}</p>{handoffPreview.sources.map((source: Entity) => <article className="source-record" key={source.id}><h3>{source.title}</h3><Status value={source.status}/><p className="preserve">{source.content}</p><span className="small mono">{source.id} · v{source.revision}</span></article>)}{handoffPreview.files.map((file: Entity) => <p key={file.id} className="small">Selected file: {file.name} · {file.size} bytes</p>)}<p className="small muted">The selected snapshot grants access to this content. The recipient can copy it. WorkTether can revoke future retrieval.</p><div className="row"><button className="secondary" disabled={busy} onClick={() => {setHandoffDraft({...handoffPreview.input, idempotencyKey: crypto.randomUUID()}); setHandoffPreview(null);}}>Edit selection</button><button className="primary" disabled={busy} onClick={() => void run('send_handoff', handoffPreview.input, 'Selected handoff delivered to the inbox.').then(() => setModal(null)).catch(() => {})}><Send size={16}/>Send selected content</button></div></div>}
      {modal === 'handoff-detail' && handoff && <div className="handoff-detail"><div className="row between"><span className="small muted">From {memberName(handoff.senderId)} · v{handoff.workRevision}</span><Status value={handoff.state} /></div>{handoff.stale && <div className="attention-banner compact"><AlertTriangle size={18} /><span>Recorded information changed after this snapshot. Confirm current requirements with the sender.</span></div>}<p className="preserve">{handoff.content}</p>{(handoff.sourceSnapshots || []).map((source: Entity) => <article className="source-record" key={source.id}><h3>{source.title}</h3><p className="preserve">{source.content}</p><span className="small muted">Selected source snapshot · v{source.revision}</span></article>)}{(handoff.attachmentIds || []).map((id: string) => <a className="attachment-link" href={`/api/attachments/${encodeURIComponent(id)}`} key={id}><Download size={16} />Download selected attachment</a>)}<div className="row">{handoff.recipientId === data.user.id && handoff.state !== 'acknowledged' && <button className="primary" disabled={busy} onClick={() => void run('acknowledge_handoff', { handoffId: handoff.id }, 'Handoff acknowledged.').then(() => setModal(null)).catch(() => {})}><Check size={16} />Acknowledge</button>}{handoff.senderId === data.user.id && <button className="secondary danger" disabled={busy} onClick={() => void run('revoke_handoff', { handoffId: handoff.id }, 'Future handoff retrieval revoked.').then(() => setModal(null)).catch(() => {})}>Revoke access</button>}</div></div>}
      {modal === 'register-device' && <form onSubmit={event => submitAction(event, 'register_device', {}, 'Client registration created.')}><FormField label="Device name"><input name="name" required maxLength={100} placeholder="e.g. Work MacBook" /></FormField><FormField label="Platform"><select name="platform"><option>macOS</option><option>Windows</option><option>Linux</option><option>Other</option></select></FormField><FormField label="AI client"><input name="client" required maxLength={100} placeholder="Client name" /></FormField><button className="primary" disabled={busy}>Register client</button></form>}
      {(modal === 'create-credential' || modal === 'setup-credential') && <>{secret ? <div className="credential-result"><p>Copy this credential now. It is shown once.</p>{modal === 'setup-credential' && <p className="small muted">Paste it into the terminal in setup step 2. Keep it out of chats and shared files.</p>}<textarea readOnly value={secret} aria-label="New MCP credential" rows={3} /><button className="primary" onClick={() => void copy(secret)}><Copy size={16} />Copy credential</button><p className="small muted">Treat it as a password. Revoke it from Manage credentials if it is lost or shared.</p>{modal === 'setup-credential' && <p className="small muted">After setup succeeds, you may revoke this setup credential; the new client credentials remain separate.</p>}</div> : <form onSubmit={event => { const fields = values(event); if (!fields.deviceId) delete fields.deviceId; void run('create_credential', fields, 'Credential created.').then(result => setSecret(result.token || result.rawToken)).catch(() => {}); }}><FormField label="Credential name"><input name="name" required maxLength={100} defaultValue={modal === 'setup-credential' ? 'Local client setup' : ''} placeholder="e.g. Work MacBook MCP" /></FormField>{modal !== 'setup-credential' && <FormField label="Registered client"><select name="deviceId"><option value="">No device association</option>{data.devices.filter(device => !device.revoked).map(device => <option value={device.id} key={device.id}>{device.name}</option>)}</select></FormField>}{modal === 'setup-credential' && <p className="small muted">Setup will create the individual client registrations for you. No manual registration is needed.</p>}<button className="primary" disabled={busy}>Create credential</button></form>}</>}
      {modal === 'share-work' && work && <form onSubmit={event => submitAction(event, 'share_work', { workId: work.id }, 'Work access granted.')}><FormField label="Collaborator"><select name="userId" required>{data.members.filter(member => member.id !== data.user.id).map(member => <option key={member.id} value={member.id}>{member.name}</option>)}</select></FormField><FormField label="Permission"><select name="permission"><option value="read">Read work and its sources</option><option value="edit">Read and edit work and its sources</option></select></FormField><p className="small muted">This grants access to the work item. Use a handoff to share selected content instead.</p><button className="primary" disabled={busy}>Grant access</button></form>}
      {modal === 'reassign-work' && work && <form onSubmit={event => submitAction(event, 'reassign_work', { workId: work.id }, 'Work ownership transferred.')}><FormField label="New owner"><select name="userId" required>{data.members.filter(member => member.id !== data.user.id).map(member => <option key={member.id} value={member.id}>{member.name}</option>)}</select></FormField><FormField label="Your access after transfer"><select name="retainAccess"><option value="read">Retain read access</option><option value="edit">Retain edit access</option><option value="none">Remove my access</option></select></FormField><button className="primary" disabled={busy}>Transfer ownership</button></form>}
      {modal === 'add-member' && project && <form onSubmit={event => submitAction(event, 'add_member', { projectId: project.id }, 'Project member added.')}><FormField label="Registered email"><input name="email" type="email" required placeholder="person@example.com" /></FormField><p className="small muted">The person must create a local account first. This shares the project baseline, not your private work.</p><button className="primary" disabled={busy}>Add member</button></form>}
      {modal === 'attachment' && work && <form onSubmit={async event => { event.preventDefault(); const fields = new FormData(event.currentTarget); const file = fields.get('file') as File; if (!file?.size || file.size > 5 * 1024 * 1024) { setError('Choose a file up to 5 MiB.'); return; } const reader = new FileReader(); reader.onload = () => { const contentBase64 = String(reader.result).split(',')[1]; const mime = file.name.toLowerCase().endsWith('.md') ? 'text/markdown' : file.type || 'text/plain'; void run('add_attachment', { workId: work.id, name: file.name, mime, contentBase64 }, 'Attachment stored with work permissions.').then(() => setModal(null)).catch(() => {}); }; reader.readAsDataURL(file); }}><FormField label="File"><input type="file" name="file" required accept=".txt,.md,.pdf,.png,.jpg,.jpeg" /></FormField><p className="small muted">Protected by this work item's access rules. File contents are not automatically added to model context.</p><button className="primary" disabled={busy}>Attach file</button></form>}
    </Modal>}
  </div>;
}
